In [1]:
import sys

print(sys.executable)

d:\Customer-Intelligence-Retention\.venv\Scripts\python.exe

In [2]:
import pandas as pd
import numpy as np
import matplotlib
import seaborn as sns
import sklearn

print("Environment ready!")
print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)
print("Scikit-learn:", sklearn.__version__)

Environment ready!
Pandas: 3.0.6
NumPy: 2.5.3
Scikit-learn: 1.9.1

In [3]:
import pandas as pd
import numpy as np

FILE_PATH = "../data/online_retail_II.xlsx"

df = pd.read_excel(FILE_PATH)

print(f"Dataset loaded successfully.")
print(f"Rows: {df.shape[0]:,}")
print(f"Columns: {df.shape[1]}")

Dataset loaded successfully.
Rows: 525,461
Columns: 8

In [4]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 525461 entries, 0 to 525460
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      525461 non-null  object
 1   StockCode    525461 non-null  object
 2   Description  522533 non-null  object
 3   Quantity     525461 non-null  int64
 4   InvoiceDate  525461 non-null  datetime64[us]
 5   Price        525461 non-null  float64
 6   Customer ID  417534 non-null  float64
 7   Country      525461 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 32.1+ MB

In [6]:
df.columns.tolist()

['Invoice',
 'StockCode',
 'Description',
 'Quantity',
 'InvoiceDate',
 'Price',
 'Customer ID',
 'Country']

In [7]:
missing = pd.DataFrame({
    "Missing Count": df.isna().sum(),
    "Missing %": (df.isna().mean() * 100).round(2)
})

missing.sort_values("Missing Count", ascending=False)

             Missing Count  Missing %
Customer ID         107927      20.54
Description           2928       0.56
StockCode                0       0.00
Invoice                  0       0.00
Quantity                 0       0.00
InvoiceDate              0       0.00
Price                    0       0.00
Country                  0       0.00

In [8]:
print(f"Duplicate rows: {df.duplicated().sum():,}")

Duplicate rows: 6,865

In [12]:
df[["Quantity", "Price"]].describe().round(2)

        Quantity      Price
count  525461.00  525461.00
mean       10.34       4.69
std       107.42     146.13
min     -9600.00  -53594.36
25%         1.00       1.25
50%         3.00       2.10
75%        10.00       4.21
max     19152.00   25111.09

In [13]:
print("Negative quantities:", (df["Quantity"] < 0).sum())
print("Zero quantities:", (df["Quantity"] == 0).sum())
print("Negative prices:", (df["Price"] < 0).sum())
print("Zero prices:", (df["Price"] == 0).sum())

Negative quantities: 12326
Zero quantities: 0
Negative prices: 3
Zero prices: 3687

In [14]:
cancelled = df["Invoice"].astype(str).str.startswith("C")

print("Cancelled transactions:", cancelled.sum())
print(
    "Cancellation percentage:",
    round(cancelled.mean() * 100, 2),
    "%"
)

Cancelled transactions: 10206
Cancellation percentage: 1.94 %

In [15]:
print("Unique invoices:", df["Invoice"].nunique())
print("Unique customers:", df["Customer ID"].nunique())
print("Unique products:", df["StockCode"].nunique())
print("Unique countries:", df["Country"].nunique())

Unique invoices: 28816
Unique customers: 4383
Unique products: 4632
Unique countries: 40

In [16]:
print("Start date:", df["InvoiceDate"].min())
print("End date:", df["InvoiceDate"].max())

Start date: 2009-12-01 07:45:00
End date: 2010-12-09 20:01:00

In [17]:
duplicates = df[df.duplicated(keep=False)].sort_values(
    by=["Invoice", "StockCode", "InvoiceDate"]
)

duplicates.head(20)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
379,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
391,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
365,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
386,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
363,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
371,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
394,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
362,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
385,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
368,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
383,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
367,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
384,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
388,489517,84951A,S/4 PISTACHIO LOVEBIRD COASTERS,1,2009-12-01 11:34:00,2.55,16329.0,United Kingdom
390,489517,84951A,S/4 PISTACHIO LOVEBIRD COASTERS,1,2009-12-01 11:34:00,2.55,16329.0,United Kingdom
634,489529,22028,PENNY FARTHING BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
657,489529,22028,PENNY FARTHING BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
656,489529,22036,DINOSAUR BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
658,489529,22036,DINOSAUR BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
628,489529,48129,DOOR MAT TOPIARY,1,2009-12-01 11:51:00,6.75,17984.0,United Kingdom

In [18]:
duplicates.shape

(13283, 8)

In [19]:
zero_price = df[df["Price"] == 0]

zero_price.head(20)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
263,489464,21733,85123a mixed,-96,2009-12-01 10:52:00,0.0,NaN,United Kingdom
283,489463,71477,short,-240,2009-12-01 10:52:00,0.0,NaN,United Kingdom
284,489467,85123A,21733 mixed,-192,2009-12-01 10:53:00,0.0,NaN,United Kingdom
470,489521,21646,NaN,-50,2009-12-01 11:44:00,0.0,NaN,United Kingdom
3114,489655,20683,NaN,-44,2009-12-01 17:26:00,0.0,NaN,United Kingdom
3161,489659,21350,NaN,230,2009-12-01 17:39:00,0.0,NaN,United Kingdom
3162,489660,35956,lost,-1043,2009-12-01 17:43:00,0.0,NaN,United Kingdom
3168,489663,35605A,damages,-117,2009-12-01 18:02:00,0.0,NaN,United Kingdom
3731,489781,84292,NaN,17,2009-12-02 11:45:00,0.0,NaN,United Kingdom
4296,489806,18010,NaN,-770,2009-12-02 12:42:00,0.0,NaN,United Kingdom
4538,489820,21133,invcd as 84879?,-720,2009-12-02 13:23:00,0.0,NaN,United Kingdom
4566,489821,85049G,NaN,-240,2009-12-02 13:25:00,0.0,NaN,United Kingdom
4674,489825,22076,6 RIBBONS EMPIRE,12,2009-12-02 13:34:00,0.0,16126.0,United Kingdom
5904,489861,DOT,DOTCOM POSTAGE,1,2009-12-02 14:50:00,0.0,NaN,United Kingdom
6378,489882,35751C,NaN,12,2009-12-02 16:22:00,0.0,NaN,United Kingdom
6555,489898,79323G,NaN,954,2009-12-03 09:40:00,0.0,NaN,United Kingdom
6556,489899,79323GR,sold as gold,-954,2009-12-03 09:41:00,0.0,NaN,United Kingdom
6576,489901,21098,NaN,-200,2009-12-03 09:47:00,0.0,NaN,United Kingdom
6581,489903,21166,NaN,48,2009-12-03 09:57:00,0.0,NaN,United Kingdom
6781,489998,48185,DOOR MAT FAIRY CAKE,2,2009-12-03 11:19:00,0.0,15658.0,United Kingdom

In [20]:
zero_price[["Invoice", "StockCode", "Description", "Quantity", "Price", "Customer ID"]].head(20)

     Invoice StockCode          Description  Quantity  Price  Customer ID
263   489464     21733         85123a mixed       -96    0.0          NaN
283   489463     71477                short      -240    0.0          NaN
284   489467    85123A          21733 mixed      -192    0.0          NaN
470   489521     21646                  NaN       -50    0.0          NaN
3114  489655     20683                  NaN       -44    0.0          NaN
3161  489659     21350                  NaN       230    0.0          NaN
3162  489660     35956                 lost     -1043    0.0          NaN
3168  489663    35605A              damages      -117    0.0          NaN
3731  489781     84292                  NaN        17    0.0          NaN
4296  489806     18010                  NaN      -770    0.0          NaN
4538  489820     21133      invcd as 84879?      -720    0.0          NaN
4566  489821    85049G                  NaN      -240    0.0          NaN
4674  489825     22076   6 RIBBONS EMPIRE          12    0.0      16126.0
5904  489861       DOT       DOTCOM POSTAGE         1    0.0          NaN
6378  489882    35751C                  NaN        12    0.0          NaN
6555  489898    79323G                  NaN       954    0.0          NaN
6556  489899   79323GR         sold as gold      -954    0.0          NaN
6576  489901     21098                  NaN      -200    0.0          NaN
6581  489903     21166                  NaN        48    0.0          NaN
6781  489998     48185  DOOR MAT FAIRY CAKE         2    0.0      15658.0

In [21]:
negative_price = df[df["Price"] < 0]

negative_price[
    ["Invoice", "StockCode", "Description", "Quantity", "Price", "Customer ID"]
]

        Invoice StockCode      Description  Quantity     Price  Customer ID
179403  A506401         B  Adjust bad debt         1 -53594.36          NaN
276274  A516228         B  Adjust bad debt         1 -44031.79          NaN
403472  A528059         B  Adjust bad debt         1 -38925.87          NaN

In [22]:
negative_qty = df["Quantity"] < 0
cancelled = df["Invoice"].astype(str).str.startswith("C")

print("Negative quantity rows:", negative_qty.sum())
print("Negative quantity + cancelled invoice:",
      (negative_qty & cancelled).sum())
print("Negative quantity + normal invoice:",
      (negative_qty & ~cancelled).sum())

Negative quantity rows: 12326
Negative quantity + cancelled invoice: 10205
Negative quantity + normal invoice: 2121

In [23]:
print(
    df.loc[
        negative_qty & ~cancelled,
        ["Invoice", "StockCode", "Description",
         "Quantity", "InvoiceDate", "Price", "Customer ID"]
    ].head(20)
)

      Invoice StockCode      Description  Quantity         InvoiceDate  Price  \
263    489464     21733     85123a mixed       -96 2009-12-01 10:52:00    0.0
283    489463     71477            short      -240 2009-12-01 10:52:00    0.0
284    489467    85123A      21733 mixed      -192 2009-12-01 10:53:00    0.0
470    489521     21646              NaN       -50 2009-12-01 11:44:00    0.0
3114   489655     20683              NaN       -44 2009-12-01 17:26:00    0.0
3162   489660     35956             lost     -1043 2009-12-01 17:43:00    0.0
3168   489663    35605A          damages      -117 2009-12-01 18:02:00    0.0
4296   489806     18010              NaN      -770 2009-12-02 12:42:00    0.0
4538   489820     21133  invcd as 84879?      -720 2009-12-02 13:23:00    0.0
4566   489821    85049G              NaN      -240 2009-12-02 13:25:00    0.0
6556   489899   79323GR     sold as gold      -954 2009-12-03 09:41:00    0.0
6576   489901     21098              NaN      -200 2009-12-03 09:47:00    0.0
6911   490007     84347            21494      -720 2009-12-03 12:09:00    0.0
7205   490016     21982              NaN     -1012 2009-12-03 12:30:00    0.0
7559   490055     20620              NaN       -25 2009-12-03 13:22:00    0.0
8553   490084     85064              NaN       -89 2009-12-03 15:37:00    0.0
9308   490130     21493            lost?      -600 2009-12-03 18:28:00    0.0
9667   490146     21558              NaN      -169 2009-12-04 09:29:00    0.0
10508  490165     21493              NaN      -106 2009-12-04 11:32:00    0.0
11973  490354     21489              NaN       -23 2009-12-04 16:39:00    0.0

       Customer ID
263            NaN
283            NaN
284            NaN
470            NaN
3114           NaN
3162           NaN
3168           NaN
4296           NaN
4538           NaN
4566           NaN
6556           NaN
6576           NaN
6911           NaN
7205           NaN
7559           NaN
8553           NaN
9308           NaN
9667           NaN
10508          NaN
11973          NaN

In [24]:
print(
    df.loc[
        negative_qty & cancelled,
        ["Invoice", "StockCode", "Description",
         "Quantity", "InvoiceDate", "Price", "Customer ID"]
    ].head(20)
)

     Invoice StockCode                          Description  Quantity  \
178  C489449     22087             PAPER BUNTING WHITE LACE       -12
179  C489449    85206A         CREAM FELT EASTER EGG BASKET        -6
180  C489449     21895        POTTING SHED SOW 'N' GROW SET        -4
181  C489449     21896                   POTTING SHED TWINE        -6
182  C489449     22083           PAPER CHAIN KIT RETRO SPOT       -12
183  C489449     21871                  SAVE THE PLANET MUG       -12
184  C489449     84946      ANTIQUE SILVER TEA GLASS ETCHED       -12
185  C489449    84970S    HANGING HEART ZINC T-LIGHT HOLDER       -24
186  C489449     22090            PAPER BUNTING RETRO SPOTS       -12
196  C489459    90200A           PURPLE SWEETHEART BRACELET        -3
197  C489459    90200D             PINK SWEETHEART BRACELET        -3
198  C489459    90200B            BLACK SWEETHEART BRACELET        -3
199  C489459    90200E            GREEN SWEETHEART BRACELET        -3
200  C489459    90200C             BLUE SWEETHEART BRACELET        -3
201  C489459    90185C       BLACK DIAMANTE EXPANDABLE RING        -3
202  C489459    90185B    AMETHYST DIAMANTE EXPANDABLE RING        -3
203  C489459    90003C  MIDNIGHT BLUE PAIR HEART HAIR SLIDE        -3
204  C489459    90003D       CRYSTAL PAIR HEART HAIR SLIDES        -3
205  C489459    90003B   ROSE COLOUR PAIR HEART HAIR SLIDES        -3
206  C489459    90209C          PINK ENAMEL+GLASS HAIR COMB        -3

            InvoiceDate  Price  Customer ID
178 2009-12-01 10:33:00   2.95      16321.0
179 2009-12-01 10:33:00   1.65      16321.0
180 2009-12-01 10:33:00   4.25      16321.0
181 2009-12-01 10:33:00   2.10      16321.0
182 2009-12-01 10:33:00   2.95      16321.0
183 2009-12-01 10:33:00   1.25      16321.0
184 2009-12-01 10:33:00   1.25      16321.0
185 2009-12-01 10:33:00   0.85      16321.0
186 2009-12-01 10:33:00   2.95      16321.0
196 2009-12-01 10:44:00   4.25      17592.0
197 2009-12-01 10:44:00   4.25      17592.0
198 2009-12-01 10:44:00   4.25      17592.0
199 2009-12-01 10:44:00   4.25      17592.0
200 2009-12-01 10:44:00   4.25      17592.0
201 2009-12-01 10:44:00   4.25      17592.0
202 2009-12-01 10:44:00   4.25      17592.0
203 2009-12-01 10:44:00   3.75      17592.0
204 2009-12-01 10:44:00   3.75      17592.0
205 2009-12-01 10:44:00   3.75      17592.0
206 2009-12-01 10:44:00   2.10      17592.0

In [26]:
# Defining each cleaning condition

missing_customer = df["Customer ID"].isna()
duplicate = df.duplicated()
non_positive_price = df["Price"] <= 0
cancelled_invoice = df["Invoice"].astype(str).str.startswith("C")
negative_quantity = df["Quantity"] < 0

print("Original rows:", len(df))

print("\nRows affected by each condition:")
print("Missing Customer ID:", missing_customer.sum())
print("Exact duplicates:", duplicate.sum())
print("Price <= 0:", non_positive_price.sum())
print("Cancelled invoices:", cancelled_invoice.sum())
print("Negative quantity:", negative_quantity.sum())

# Proposed clean dataset
clean_mask = (
    ~missing_customer
    & ~duplicate
    & ~non_positive_price
    & ~cancelled_invoice
    & ~negative_quantity
)

print("\nRows remaining after ALL rules:", clean_mask.sum())
print("Rows removed:", (~clean_mask).sum())
print(
    "Percentage retained:",
    round(clean_mask.mean() * 100, 2),
    "%"
)

Original rows: 525461

Rows affected by each condition:
Missing Customer ID: 107927
Exact duplicates: 6865
Price <= 0: 3690
Cancelled invoices: 10206
Negative quantity: 12326

Rows remaining after ALL rules: 400916
Rows removed: 124545
Percentage retained: 76.3 %

In [27]:
# Creating the clean customer-sales dataset

df_clean = df.loc[clean_mask].copy()

print("Clean dataset shape:", df_clean.shape)

print("\nRemaining missing values:")
print(df_clean.isna().sum())

print("\nRemaining negative quantities:",
      (df_clean["Quantity"] < 0).sum())

print("Remaining non-positive prices:",
      (df_clean["Price"] <= 0).sum())

print("Remaining cancelled invoices:",
      df_clean["Invoice"].astype(str).str.startswith("C").sum())

print("Remaining duplicate rows:",
      df_clean.duplicated().sum())

Clean dataset shape: (400916, 8)

Remaining missing values:
Invoice        0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
Price          0
Customer ID    0
Country        0
dtype: int64

Remaining negative quantities: 0
Remaining non-positive prices: 0
Remaining cancelled invoices: 0
Remaining duplicate rows: 0

In [28]:
# Saving cleaned transaction data for downstream analysis

CLEAN_FILE_PATH = "../data/clean_transactions.csv"

df_clean.to_csv(CLEAN_FILE_PATH, index=False)

print(f"Clean dataset saved to: {CLEAN_FILE_PATH}")
print(f"Rows: {len(df_clean):,}")

Clean dataset saved to: ../data/clean_transactions.csv
Rows: 400,916